# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22951cd18f892717400d7ff25bd5390d66a6468ce4cd55356b0c88490f93569c8d1807976c1e5467768cbdee951f7d5355dab226b4894175eee098995346d434

test:
  secret_key_base: 80c368d26840238f837875435acdb7bdad718b407465487e8c71f0790827014c9cf684282526f7b590f5ab89e4d0bd190586712af0f82ff64ff0da862dd89a86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
